parameters:
    ezplatform.oauth2.scopes: []

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    ### Controllers

    AdamWojs\EzPlatformOAuth2Bundle\Controller\OAuth2ClientController:
        tags: ['controller.service_arguments']

    AdamWojs\EzPlatformOAuth2Bundle\Controller\OAuth2ProfileController:
        tags: ['controller.service_arguments']

    ### Forms

    AdamWojs\EzPlatformOAuth2Bundle\Form\Type\ScopeChoiceType:
        arguments:
            $scopes: '%ezplatform.oauth2.scopes%'

    AdamWojs\EzPlatformOAuth2Bundle\Form\Type\ClientCheckboxType: ~

    ### Menus

    AdamWojs\EzPlatformOAuth2Bundle\Menu\Builder\ClientCreateRightSidebarBuilder:
        public: true
        tags:
            - { name: knp_menu.menu_builder, method: build, alias: ezplatform_oauth2.menu_configure.client.create_sidebar_right }

    AdamWojs\EzPlatformOAuth2Bundle\Menu\Builder\ClientUpdateRightSidebarBuilder:
        public: true
        tags:
            - { name: knp_menu.menu_builder, method: build, alias: ezplatform_oauth2.menu_configure.client.update_sidebar_right }

    AdamWojs\EzPlatformOAuth2Bundle\Menu\Listener\ConfigureMainMenuListener:
        tags:
            - { name: kernel.event_listener, event: ezplatform_admin_ui.menu_configure.main_menu, method: onMenuConfigure, priority: 10 }

    ### Others

    AdamWojs\EzPlatformOAuth2Bundle\EventListener\OAuth2AuthorizationSubscriber: ~
